{
 "title": "NodeJS Service Stats",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Service",
    "query": {
     "query": "label_values(nstats_activeSockets, app)"
    }
   },
   {
    "name": "timebuckets",
    "query": {
     "query": "query_result(${__range_s} / 48)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\n<h2>$Service</h2>\n</center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Packets Per Seconds",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(nstats_totalPackets{app=~\"$Service\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Http Requests ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(nstats_totalPackets{app=~\"$Service\"})"
    }
   ]
  },
  {
   "title": "Http Sucess",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(nstats_http_request_count{app=~\"$Service\",status=~\"(1|2|3)..\"})"
    }
   ]
  },
  {
   "title": "Http Errors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nstats_http_request_count{status!~\"(1|2|3)..\",app=~\"$Service\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(nstats_uptime{app=~\"$Service\"})"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nstats_uptime{app=~\"$Service\"})"
    }
   ]
  },
  {
   "title": "Active Sockets",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nstats_activeSockets{app=~\"$Service\"})"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(nstats_totalBytesWritten{app=~\"$Service\"}[2s]))"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(nstats_totalBytesRead{app=~\"$Service\"}[2s]))"
    }
   ]
  },
  {
   "title": "Avg Packets Per Second",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nstats_totalPackets{app=~\"$Service\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nstats_totalMemory{app=~\"$Service\"})"
    }
   ]
  },
  {
   "title": "Avg Response Overhead",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  sum((sum(irate(nstats_responseOverheadHistogram_sum{app=~\"$Service\"}[2s])) by (app)/ count(nstats_uptime{app=~\"$Service\"}) by (app)))  / \n  sum((sum(irate(nstats_responseOverheadHistogram_count{app=~\"$Service\"}[2s])) by (app)/ count(nstats_uptime{app=~\"$Service\"}) by (app)))\n) > 0 \n\nor\n\n((\n  sum((sum(irate(nstats_responseOverheadHistogram_sum{app=~\"$Service\"}[2s])) by (app)/ count(nstats_uptime{app=~\"$Service\"}) by (app)))  / \n  sum((sum(irate(nstats_responseOverheadHistogram_count{app=~\"$Service\"}[2s])) by (app)/ count(nstats_uptime{app=~\"$Service\"}) by (app)))\n) > bool 0) < 1",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Highest Response",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(topk(1,(delta(nstats_http_request_response_time_count{app=~\"$Service\"}[2s])) / (delta(nstats_http_request_count{app=~\"$Service\"}[2s])) > 0))"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(nstats_server_version{app=~\"$Service\"}) by (app,major,minor,patch)",
     "legendFormat": "v{{major}}.{{minor}}.{{patch}}"
    }
   ]
  },
  {
   "title": "Total Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\"nstats_totalBytes.*\",app=~\"$Service\"})"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20,sum(delta(nstats_http_request_count{app=~\"$Service\", status=~\"2..|3..\"}[$__range])) by (method,route, app) > 0)",
     "legendFormat": "[{{app}}] {{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Response Times  Avg",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 10, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(20,(sum(delta(nstats_http_request_response_time_count{app=~\"$Service\"}[$__range])) by (route,method)) / (sum(delta(nstats_http_request_count{app=~\"$Service\"}[$__range])) by (route,method)) > 0)",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\nsum(delta(nstats_http_request_count{app=~\"$Service\", status!~\"2..|3..\"}[$__range])) / sum(delta(nstats_http_request_count{app=~\"$Service\"}[$__range]))"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(nstats_http_request_count{app=~\"$Service\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20,sum(delta(nstats_http_request_count{app=~\"$Service\", status!~\"2..|3..\"}[$__range])) by (method,route, app) > 0)",
     "legendFormat": "[{{app}}] {{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Request Per Second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nstats_totalPackets{app=~\"$Service\"}[2s])) by (app) > 0",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Response Overhead Histogram Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(le) (changes(nstats_responseOverheadHistogram_bucket{app=~\"$Service\"}[${timebuckets}s]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "((sum(rate(nstats_responseOverheadHistogram_sum{app=~\"$Service\"}[$__rate_interval])) by (app)/ count(nstats_uptime{app=~\"$Service\"}) by (app)) / (sum(rate(nstats_responseOverheadHistogram_count{app=~\"$Service\"}[$__rate_interval])) by (app)/ count(nstats_uptime{app=~\"$Service\"}) by (app))) > 0",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nstats_activeSockets{app=~\"$Service\"})",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}